import type { Metadata } from "next";
import { Playfair_Display, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import TopHeader from "./components/ٌTopHeader";
import MainHeader from "./components/MainHeader";

const Playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${Playfair.variable} ${roboto.variable} antialiased`}>
        <header>
          <TopHeader />
          <MainHeader />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
